### ISSUE TITLE
 Extension not renaming tabs

### ISSUE THREAD

**Issue by SaidTorres3** [Luke-Callaghan23/VSCode-Tab-Labels#1]
I'm experiencing an issue where the extension is not renaming tabs as expected.

Steps to Reproduce:

- Open VS Code (version 1.90.2).
- Rename a tab.
- Observe that the tabs are not renamed, regarding of them being added to ```settings.json```.

Expected Behavior: Tabs should be renamed based on the configurations specified in the settings.json file.
Actual Behavior: None of the tab names are renamed.

Environment:
VS Code Version: 1.90.2
Operating System: Windows 11
Extension Version: v0.0.1

Additional Information:
The settings.json file appears to be configured correctly as tabs are being added, but renaming does not occur.
I have tried restarting VS Code and reinstalling the extension without success.

**Comment by Luke-Callaghan23** [comment]
Hey @SaidTorres3 in the monthly update from a couple months ago, VSCode now requires tab paths to be formatted differently and I forgot to update the extension.  Latest release 0.0.2 should fix this.  Please let me know if it's working for you now

**Comment by SaidTorres3** [comment]
Now it works!

All tabs that do not belong to the project (including new unsaved documents) are not being renamed, but that is expected as how the extension is working right now.
